[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
